### ISSUE TITLE
USENIX Security 2022 Summer deadline results

### ISSUE THREAD

**Issue by vahldiek** [secartifacts/secartifacts.github.io#11]
@cgiuffr @clementine-m: If you post the csv/excel or so from HotCRP with the results of USENIX 2022 Summer deadline, I can add it to the results page.

**Comment by cgiuffr** [comment]
See all the summer results here: https://www.dropbox.com/s/anu4vlkob89gwrb/sec22winterae-results.csv?dl=1

Note: they should be all final, but the authors of "One-off Disclosure Control" still haven't submitted the final artifact URL. If that changes wrt the submitted version, I'll let you  know.

**Comment by vahldiek** [comment]
Updated according to your CSV. Thanks!
